- name: Hello World Sample
  hosts: 192.168.122.13
  tasks:
    - name: Hello Message
      debug:
       msg: "Hello World!"
    - hostname: name=controller.sabe.com
    - redhat_subscription: state='present' username=m.pineda password='redhat2016!.-' autosubscribe=true
